### ISSUE TITLE
Install fails on Synology

### ISSUE THREAD

**Issue by carldavis** [JonathanTreffler/backblaze-personal-wine-container#185]
I think the download is failing but I do not know how to confirm or how to further troubleshoot. The container will remain at ```wine64 install_backblaze.exe``` until I bring that window to the foreground, afterwards all I have is a black screen.

Any assistance is appreciated.

DSM 7.1.1-42962 Update 1
DS1817+


```
[app         ] + wine64 install_backblaze.exe                                                                                                                                                                                                                                         
[app         ] + start_app                                                                                                                                                 
[app         ] ++ cat /config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt                                                                 
[app         ] cat: '/config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt': No such file or directory                                      
[app         ] + log_message 'STARTAPP: Starting Backblaze version '                                                                                                       
[app         ] ++ date                                                                                                                                                     
[app         ] + echo 'Sun Sep  1 08:27:34 PM UTC 2024: STARTAPP: Starting Backblaze version '                                                                             
[app         ] + sleep infinity                                                                                                                                            
[app         ] + wine64 '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' -noquiet                                                                            
[app         ] wine: failed to open "/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe": c0000135                           
```

**Comment by jan-oratowski** [comment]
Hi @carldavis 

Have you managed to install it?

I have simmilar setup (DS1515+ upgraded to DS1517+ firmware with DSM 7.2-64570 Update 3) and I'm running this container for a year.

I had initial problems with setting it up, but found somewhere the Ubuntu 20 image will not work on Synology, so had to use Ubuntu 18 image.

Here is my docker-compose.yaml:

```
version: '3.1'

services:

  backblaze:
    image: tessypowder/backblaze-personal-wine:ubuntu18
    container_name: backblaze_backup
    restart: on-failure:5
    ports:
      - 5800:5800
    environment:
      S6_BEHAVIOUR_IF_STAGE2_FAILS: 3
      S6_SERVICE_DEPS: 1
      USER_ID: 1028
      GROUP_ID: 100
      VNC_PASSWORD: <your pass here>
      APP_NAME: Backblaze Personal Backup
      APP_USER: app
      XDG_DATA_HOME: /config/xdg/data
      XDG_CONFIG_HOME: /config/xdg/config
      XDG_CACHE_HOME: /config/xdg/cache
      XDG_RUNTIME_DIR: /tmp/run/user/app
      DISPLAY: :0
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 1024
      WINEPREFIX: /config/wine/
      LANG: en_US.UTF-8
      WINEDEBUG: -all
    volumes:
      - /volume1/docker/backblaze:/config
```
