### ISSUE TITLE
Add Docker Compose and Swag config to docs

### ISSUE THREAD

**Issue by BinaryShrub** [JonathanTreffler/backblaze-personal-wine-container#92]
would be helpful to have a command like this in the docs for docker compose

```
  backblaze:
    container_name: backblaze
    image: tessypowder/backblaze-personal-wine:latest
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - /home/<user>/backblaze:/config
      - /data:/drive_d
```

you can even remove the need for an open port if you set it up with `swag`:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name bb.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        
        proxy_pass http://backblaze:5800;
    }

}
```

Now I can access it with https://bb.<my_domain>.com
